version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "marcus"  # Replace with your GitHub username
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "xgboost"
        update-types: ["version-update:semver-major"]
      - dependency-name: "scikit-learn"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all development dependencies together
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "black"
          - "mypy"
          - "bandit"
          - "pre-commit"
          - "hypothesis"
      # Group all ML-related dependencies
      ml-dependencies:
        patterns:
          - "numpy"
          - "pandas"
          - "scikit-learn"
          - "xgboost"
          - "torch"
          - "optuna"
          - "mlflow"
      # Group all security tools
      security-tools:
        patterns:
          - "pip-audit"
          - "safety"
          - "bandit"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 3
    reviewers:
      - "marcus"  # Replace with your GitHub username
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/deployment"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 2
    reviewers:
      - "marcus"  # Replace with your GitHub username
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"