version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=crypto_data
      - DB_HOST=postgres
      - DB_PORT=5432
    # A montagem de volume foi removida para evitar conflitos com o ambiente de dev container.
    # Os arquivos da aplicação agora são copiados para a imagem no Dockerfile.
    # volumes:
    #   - .:/workspaces:cached
    # Mantém o contêiner rodando
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: crypto-data-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_data
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: crypto-collector
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: strongpassword
    command: python collector.py

volumes:
  postgres_data:
    driver: local
