FROM python:3.11-slim

# Definindo diretório de trabalho
WORKDIR /app

# Copiar dependências e instalar
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o script coletor e arquivos de configuração
COPY collector.py ./
COPY .env ./

# Comando padrão
CMD ["python", "collector.py"]
