name: ic-marcus
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - pandas=2.0.0
  - numpy=1.24.0
  - sqlalchemy=2.0.0
  - alembic=1.11.0
  - pydantic=2.0.0
  - pydantic-settings=2.0.0
  - python-dotenv=1.0.0
  - requests=2.31.0
  - websocket-client=1.6.0
  - aiohttp=3.8.0
  - psycopg2-binary=2.9.0
  - fastapi=0.104.0
  - uvicorn=0.24.0
  - jinja2=3.1.0
  - prometheus-client=0.17.0
  - json-logging=1.3.0
  - apscheduler=3.10.0
  - schedule=1.2.0
  - matplotlib=3.7.0
  - seaborn=0.12.0
  - pyarrow=14.0.0
  - pytest=7.4.0
  - pytest-asyncio=0.21.0
  - pytest-cov=4.1.0
  - black=23.0.0
  - isort=5.12.0
  - flake8=6.0.0
  - mypy=1.5.0
  - gunicorn=21.2.0
  - redis=4.6.0
  - celery=5.3.0
  - slack-sdk=3.21.0
  - discord-webhook=1.3.0
  - cryptography=41.0.0
  - bcrypt=4.0.0
  - cython=3.0.0
  - numba=0.57.0
  - arch=6.3.0
  - ta=0.10.0
  - talib=0.4.25
  - pywavelets=1.4.1
  - tensorflow=2.17.0
  - keras-tuner=1.4.0
  - xgboost=2.0.0
  - optuna=3.0.0
  - scipy=1.9.0
  - shap=0.42.0
  - statsmodels=0.14.0
  - polars=0.20.0
  - pylint
