# configs/data.yaml - Configurações de dados e features
# Configurações seguindo CLAUDE.md e PRDs

# Dados base
data:
  symbols: ["BTCUSDT", "ETHUSDT", "ADAUSDT", "DOTUSDT"]
  timeframes: ["5m", "15m", "1h", "4h"]
  start_date: "2020-01-01"
  end_date: "2024-12-31"
  timezone: "UTC"  # timezone-aware obrigatório

# Unidades padronizadas
units:
  returns: "log"    # log returns
  costs: "bps"      # basis points

# Configurações de cache
cache:
  enabled: true
  path: "data/processed"
  format: "parquet"
  compress: "snappy"

# Feature Engineering
features:
  # Períodos básicos para indicadores
  lookback_periods: [5, 10, 20, 50, 100, 200]

  # Features de preço
  price_features:
    - returns
    - log_returns
    - realized_volatility
    - price_momentum
    - price_acceleration

  # Indicadores técnicos
  technical_indicators:
    rsi:
      periods: [14, 21, 30]
    macd:
      fast: 12
      slow: 26
      signal: 9
    bollinger_bands:
      period: 20
      std: 2
    atr:
      period: 14
    stochastic:
      k_period: 14
      d_period: 3

  # Features avançadas (PRDs)
  microstructure:
    enabled: true
    features:
      - order_book_imbalance
      - vpin
      - kyle_lambda
      - roll_measure
      - amihud_illiquidity

  derivatives:
    enabled: true
    features:
      - funding_rate
      - open_interest_ratio
      - liquidation_levels
      - basis_spread

# Labeling - Sistema Vol-Aware (Substitui Triple Barrier)
labels:
  method: "vol_threshold"  # Volatility-scaled threshold labeling
  
  # Configurações de vol-threshold
  vol_threshold:
    # Estimadores de volatilidade disponíveis
    estimator: "yang_zhang"  # atr, garman_klass, yang_zhang, parkinson, realized
    lookback: 64            # Janela para cálculo de volatilidade (em barras)
    
    # Multiplicador k (hiperparâmetro a otimizar)
    k:
      grid: [0.5, 0.75, 1.0, 1.25, 1.5, 2.0]  # Valores para grid search
      default: 1.0                              # Valor padrão
    
    # Zona neutra
    neutral_zone: true          # Se False, apenas binário (-1, 1)
    min_threshold: 0.001       # Threshold mínimo (0.1%)
    max_threshold: 0.10        # Threshold máximo (10%)
    
    # Configurações por horizonte (em barras de 15m)
    horizons:
      "15m": 1     # 1 bar = 15 minutos
      "30m": 2     # 2 bars = 30 minutos
      "60m": 4     # 4 bars = 60 minutos
      "120m": 8    # 8 bars = 120 minutos
      "240m": 16   # 16 bars = 240 minutos
      "480m": 32   # 32 bars = 480 minutos (8h)
    
    # Critérios de qualidade
    min_class_ratio: 0.1       # Abortar se classe positiva < 10%
    max_neutral_ratio: 0.6     # Abortar se neutros > 60%
    
    # Sample weights
    sample_weights:
      method: "balanced"        # balanced, sqrt, none
      decay_factor: 0.99       # Decaimento temporal
      
  # Legacy support (mantido para compatibilidade)
  directional:
    min_return_threshold: 0.005  # 0.5% mínimo para filtrar ruído
    use_volatility_weights: true  # Migrar para vol_threshold.sample_weights

# Configurações de Trading (para threshold baseado em lucro)
trading:
  # Custos de transação (realistas para criptomoedas)
  costs:
    fee_bps: 10        # 0.1% fee (Binance spot)
    slippage_bps: 10   # 0.1% slippage estimado
    cost_per_trade: 0.002  # 0.2% total (fee + slippage)

  # Retornos esperados
  returns:
    win_return: 0.010      # 1.0% retorno médio por trade correto (mais conservador)
    loss_return: 0.010     # 1.0% perda média por trade incorreto

  # Configurações de threshold
  threshold:
    min_threshold: 0.1     # Threshold mínimo para testar
    max_threshold: 0.9     # Threshold máximo para testar
    n_thresholds: 100      # Número de thresholds para testar

# Splits temporais
split:
  method: "purged_kfold"
  test_size: 0.2
  val_size: 0.2

  # Purged K-Fold
  purged_kfold:
    n_splits: 5
    embargo: 10  # barras de embargo

  # Walk Forward (alternativo)
  walk_forward:
    n_splits: 5
    gap: 5       # gap entre treino e validação

# Validação de schemas
schema:
  validate_on_load: true
  required_columns: ["open", "high", "low", "close", "volume"]
  datetime_index: true
  allow_na_ratio: 0.05  # Máximo 5% de NAs permitidos

# Configurações de performance
performance:
  chunk_size: 10000
  parallel_processing: true
  n_jobs: -1  # Usar todos os cores disponíveis

# Logging
logging:
  level: "INFO"
  format: "structured"
  include_timings: true
